version: '2.4'

services:
  jenkins:
    build: ./jenkins_controller
    container_name: jenkins
    ports:
      - 8880:8080
      - 5000:5000
    restart: always
    volumes:
      - ./jenkins_controller/jenkins.yml:/usr/share/jenkins/ref/jenkins.yaml

  sonarqube:
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    depends_on:
      - jenkins
    ports:
      - 9000:9000
    
    restart: always
